spring:

  application:
    name: gateway-service

---
spring:

  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://${username}:${password}@localhost:9000

---
spring:
  config:
    activate:
      on-profile: live

    import: "aws-secretsmanager:/secret/calendar,optional:configserver:http://${secrets.username}:${secrets.password}@config-server:9000"

